In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('500112.csv')

In [7]:
df

        stock      bond       mm
0     20.2553   262.935   100.00
1     25.6860   268.730   102.33
2     23.4297   284.090   105.33
3     28.7463   289.162   108.89
4     33.4484   299.894   113.08
5     37.5813   302.695   117.97
6     33.7839   318.695   124.34
7     41.8725   309.103   129.94
8     46.4795   316.051   137.77
9     42.5448   298.249   150.12
10    44.2212   354.671   157.48
11    50.5451   394.532   164.00
12    60.1461   403.942   172.74
13    51.3114   417.252   189.93
14    37.7306   433.927   206.13
15    51.7772   457.885   216.85
16    64.1659   529.141   226.93
17    59.5739   531.144   241.82
18    63.4884   524.435   266.07
19    75.3032   531.040   302.74
20    99.7795   517.860   359.96
21    94.8671   538.769   404.48
22   115.3080   777.332   440.68
23   141.3160   787.357   482.42
24   150.1810   907.712   522.84
25   197.8290  1200.630   566.08
26   234.7550  1469.450   605.20
27   247.0800  1424.910   646.17
28   288.1160  1522.400   702.77
29   379.4090  1804.630   762.16
30   367.6360  1944.250   817.87
31   479.6330  2320.640   854.10
32   516.1780  2490.970   879.04
33   568.2020  2816.400   905.06
34   575.7050  2610.120   954.39
35   792.0420  3287.270  1007.84
36   973.8970  3291.580  1061.15
37  1298.8200  3687.330  1119.51
38  1670.0100  4220.240  1171.91
39  2021.4000  3903.320  1234.02
40  1837.3600  4575.330  1313.00
41  1618.9800  4827.260  1336.89
42  1261.1800  5558.400  1353.47
43  1622.9400  5588.190  1366.73

In [6]:
# Dropping extra columns
df.drop(['year'], axis=1, inplace=True)
axis = df.shape

In [8]:
no_of_stocks = axis[1]
columns = df.columns

In [9]:
# Step 1 calculate returns (stockT2 - stockT1)/stockT1
returns = pd.DataFrame(index=range(axis[0]), columns=range(axis[1]))
for idx, col in enumerate(columns):
    for i in range(1, len(df[col])):
        s1 = df[col][i - 1]
        s2 = df[col][i]
        return_value = (s2 - s1) / s1
        returns[idx][i] = return_value

# returns = returns*100
returns.drop([0], axis=0, inplace=True)

In [10]:
returns

           0         1         2
1   0.268113   0.02204    0.0233
2  -0.087842  0.057158  0.029317
3   0.226917  0.017853  0.033799
4   0.163572  0.037114  0.038479
5    0.12356   0.00934  0.043244
6  -0.101045  0.052858  0.053997
7   0.239422 -0.030098  0.045038
8   0.110024  0.022478  0.060259
9  -0.084655 -0.056326  0.089642
10  0.039403  0.189177  0.049027
11  0.143006  0.112389  0.041402
12  0.189949  0.023851  0.053293
13 -0.146887   0.03295  0.099514
14 -0.264674  0.039964  0.085295
15  0.372287  0.055212  0.052006
16  0.239269   0.15562  0.046484
17 -0.071564  0.003785  0.065615
18  0.065708 -0.012631  0.100281
19  0.186094  0.012595  0.137821
20  0.325037 -0.024819  0.189007
21 -0.049233  0.040376   0.12368
22  0.215469  0.442793  0.089498
23  0.225552  0.012897  0.094717
24  0.062732   0.15286  0.083786
25   0.31727  0.322699  0.082702
26  0.186656  0.223899  0.069107
27  0.052502 -0.030311  0.067697
28  0.166084  0.068418  0.087593
29  0.316862  0.185385  0.084508
30  -0.03103  0.077368  0.073095
31  0.304641  0.193591  0.044298
32  0.076194  0.073398    0.0292
33  0.100787  0.130644    0.0296
34  0.013205 -0.073242  0.054505
35  0.375778  0.259433  0.056004
36  0.229603  0.001311  0.052895
37  0.333632  0.120231  0.054997
38   0.28579  0.144525  0.046806
39  0.210412 -0.075095  0.052999
40 -0.091046  0.172164  0.064002
41 -0.118855  0.055063  0.018195
42 -0.221003  0.151461  0.012402
43  0.286842  0.005359  0.009797

In [11]:
# Step 2 Calculation of Σ Covariance matrix between stocks from csv
Σ = returns.cov()

In [12]:
# Step 3 calcuating quadtric programming equation or objective function

In [13]:
# Step 3 calcualting geomean of returns constraint 1
returns_for_geomean = returns + 1
returns_for_geomean[0]
geo_mean = [
    (returns_for_geomean[i].prod() ** (1 / len(returns_for_geomean[i])) - 1)
    for i in returns_for_geomean
]
geo_mean = pd.DataFrame(geo_mean)

Σ.to_csv('covariance_matrix.csv', index=False)
geo_mean.to_csv('geomean.csv', index=False)

In [18]:
# Step 5 mean and of returns
µ = returns.mean()
µ.to_csv('mean_of_returns.csv', index=False)